# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app_bundle.menu:
        class: AppBundle\Menu\Builder
        arguments: ["@knp_menu.factory"]

    app_bundle.main.menu:
        class: Knp\Menu\MenuItem
        factory: ['@app_bundle.menu', mainMenu]
        arguments : ['@security.context', '@fire_php']
        tags:
            - {name: knp_menu.menu, alias: app_main_menu}

